### ISSUE TITLE
config.json中的privkey是指的什么私钥

### ISSUE THREAD

**Issue by netmebtc** [bigbangcore/BigBangPool#1]
你好，我想建一个矿池，注意到config.json中有个参数“privkey”，请问这个参数是指的什么私钥？怎么生成的？

**Comment by wahaobi** [comment]
你设置好没

**Comment by rlinxy** [comment]
https://github.com/bigbangcore/BigBang/wiki/POW%E6%93%8D%E4%BD%9C%E6%8C%87%E5%8D%97
看这
